### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SebDominguez** [oceanofthelost/InteractiveBOM#17]
Thanks you very much for this plugin.
This is the features that I wish this add-on could do

### Include non PCB parts
I'm looking for a BOM ULP that is able to generate a BOM including non PCB parts.
At first I was using BOM-EX but with this ULP I had to maintain a text database and I can't find it anything useful. The only great thing with BOM-EX is that on your part you can add an attribute `BOM` with the value `INCLUDED` or `EXCLUDED`.
This is useful as in many project I do have non PCB / Board parts that I want in my BOM (stands off, screws, power supply, fans, socketed ic, cable harness for instance).

Every BOM ULP for eagle just ignore parts that doesn't have footprint for the BOM and this just doesn't make any sens for me.
 
### Export to PDF / CSV
It would be so nice to be able to generate a printable friendly version of the ibom webview or to export the output to CSV so it can be imported into another piece of software

### Curved board outlines
I don't know if this is due to the last version of eagle that I'm using but all my curved shapes looks like the Tesla Cybertruck.

![Capture d'écran 2019-12-03 10 33 06](https://user-images.githubusercontent.com/52816569/70038390-6e7be300-15b8-11ea-8c41-222ea1bb3c72.png)
![Capture d'écran 2019-12-03 10 33 25](https://user-images.githubusercontent.com/52816569/70038400-7176d380-15b8-11ea-9eaa-465148fdf71f.png)

**Comment by oceanofthelost** [comment]
Each feature that you are asking for are things that I would like to add to iBOM. Ill add them to feature request list. 

It looks like I might be able to start working on these in a couple of weeks.

**Comment by oceanofthelost** [comment]
Started work on these items. All three feature requests will be integrated into version 2, but it is a about a moth out since the entire front end is being redone.

**Comment by oceanofthelost** [comment]
I split this request into three feature requests in order to track each request individually.
