### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by dronecz** [oceanofthelost/InteractiveBOM#5]
I did play a bit with iBOM and for me, and hope for others, could be good to have this:

- **Quick search clear** : what about **X** at the end of the line which will clear value in search line? 
- **Color change for highlighted part**: if I check part as placed, would be possile to change color to greeen so I don´t have to worry about it anymore.
- **Hide placed parts**: if part is placed, hide the line with it so I will see just parts which have to be placed. I imagine this as **checkbox**, same as **Dark mode** in settings.  

I looked at JS file and CSS, but do not know, where to edit this. 

Thx 😉

**Comment by oceanofthelost** [comment]
Ill look into this. JS and CSS are not my normal programming languages, But I do agree that these would be good additions.

**Comment by oceanofthelost** [comment]
Color change of placed part currently implemented in 74213910db1b9b92ef256e4b44553e66b0b53fed, the current head of development commit.

**Comment by oceanofthelost** [comment]
Added "Quick Search Clear" to filter bar. Added in commit e4a67119ba13dd7d75aafb8c59a01b3e02f4cdff.

**Comment by oceanofthelost** [comment]
Added "Hide Placed Part" option to settings tab in commit e70603993a34e5a2570f58bcf404cf3e361e50a2

**Comment by oceanofthelost** [comment]
### Feature Request Summary

1. Quick Search Clear: 74213910db1b9b92ef256e4b44553e66b0b53fed
2. Color Change For Highlighted Part: e4a67119ba13dd7d75aafb8c59a01b3e02f4cdff
3. Hide Placed Parts: e70603993a34e5a2570f58bcf404cf3e361e50a2
